program HiDriver.Api;

{$APPTYPE CONSOLE}

{$R *.res}

uses
  System.SysUtils,
  ApiConfigIntf in 'Config\Interfaces\ApiConfigIntf.pas',
  ApiConfig in 'Config\Implementations\ApiConfig.pas',
  AppBootstrapIntf in 'Config\Interfaces\AppBootstrapIntf.pas',
  AppBootstrap in 'Config\Implementations\AppBootstrap.pas',
  HealthControllerIntf in 'Controllers\Interfaces\HealthControllerIntf.pas',
  HealthController in 'Controllers\Implementations\HealthController.pas',
  AuthControllerIntf in 'Controllers\Interfaces\AuthControllerIntf.pas',
  AuthController in 'Controllers\Implementations\AuthController.pas',
  ProductControllerIntf in 'Controllers\Interfaces\ProductControllerIntf.pas',
  ProductController in 'Controllers\Implementations\ProductController.pas',
  CustomerControllerIntf in 'Controllers\Interfaces\CustomerControllerIntf.pas',
  CustomerController in 'Controllers\Implementations\CustomerController.pas',
  CashRegisterControllerIntf in 'Controllers\Interfaces\CashRegisterControllerIntf.pas',
  CashRegisterController in 'Controllers\Implementations\CashRegisterController.pas',
  SaleControllerIntf in 'Controllers\Interfaces\SaleControllerIntf.pas',
  SaleController in 'Controllers\Implementations\SaleController.pas',
  AccountReceivableControllerIntf in 'Controllers\Interfaces\AccountReceivableControllerIntf.pas',
  AccountReceivableController in 'Controllers\Implementations\AccountReceivableController.pas',
  StockMovementControllerIntf in 'Controllers\Interfaces\StockMovementControllerIntf.pas',
  StockMovementController in 'Controllers\Implementations\StockMovementController.pas',
  ReceiptControllerIntf in 'Controllers\Interfaces\ReceiptControllerIntf.pas',
  ReceiptController in 'Controllers\Implementations\ReceiptController.pas',
  AuthAppServiceIntf in 'Services\Interfaces\AuthAppServiceIntf.pas',
  AuthAppService in 'Services\Implementations\AuthAppService.pas',
  ProductAppServiceIntf in 'Services\Interfaces\ProductAppServiceIntf.pas',
  ProductAppService in 'Services\Implementations\ProductAppService.pas',
  CustomerAppServiceIntf in 'Services\Interfaces\CustomerAppServiceIntf.pas',
  CustomerAppService in 'Services\Implementations\CustomerAppService.pas',
  CashRegisterAppServiceIntf in 'Services\Interfaces\CashRegisterAppServiceIntf.pas',
  CashRegisterAppService in 'Services\Implementations\CashRegisterAppService.pas',
  SaleAppServiceIntf in 'Services\Interfaces\SaleAppServiceIntf.pas',
  SaleAppService in 'Services\Implementations\SaleAppService.pas',
  AccountReceivableAppServiceIntf in 'Services\Interfaces\AccountReceivableAppServiceIntf.pas',
  AccountReceivableAppService in 'Services\Implementations\AccountReceivableAppService.pas',
  StockMovementAppServiceIntf in 'Services\Interfaces\StockMovementAppServiceIntf.pas',
  StockMovementAppService in 'Services\Implementations\StockMovementAppService.pas',
  JwtServiceIntf in 'Services\Interfaces\JwtServiceIntf.pas',
  JwtService in 'Services\Implementations\JwtService.pas',
  ReceiptAppServiceIntf in 'Services\Interfaces\ReceiptAppServiceIntf.pas',
  ReceiptAppService in 'Services\Implementations\ReceiptAppService.pas',
  AuthMiddlewareIntf in 'Middlewares\Interfaces\AuthMiddlewareIntf.pas',
  AuthMiddleware in 'Middlewares\Implementations\AuthMiddleware.pas',
  AuthValidatorIntf in 'Validators\Interfaces\AuthValidatorIntf.pas',
  AuthValidator in 'Validators\Implementations\AuthValidator.pas',
  ProductValidatorIntf in 'Validators\Interfaces\ProductValidatorIntf.pas',
  ProductValidator in 'Validators\Implementations\ProductValidator.pas',
  CustomerValidatorIntf in 'Validators\Interfaces\CustomerValidatorIntf.pas',
  CustomerValidator in 'Validators\Implementations\CustomerValidator.pas',
  CashRegisterValidatorIntf in 'Validators\Interfaces\CashRegisterValidatorIntf.pas',
  CashRegisterValidator in 'Validators\Implementations\CashRegisterValidator.pas',
  SaleValidatorIntf in 'Validators\Interfaces\SaleValidatorIntf.pas',
  SaleValidator in 'Validators\Implementations\SaleValidator.pas',
  AccountReceivableValidatorIntf in 'Validators\Interfaces\AccountReceivableValidatorIntf.pas',
  AccountReceivableValidator in 'Validators\Implementations\AccountReceivableValidator.pas',
  StockMovementValidatorIntf in 'Validators\Interfaces\StockMovementValidatorIntf.pas',
  StockMovementValidator in 'Validators\Implementations\StockMovementValidator.pas',
  ReceiptValidatorIntf in 'Validators\Interfaces\ReceiptValidatorIntf.pas',
  ReceiptValidator in 'Validators\Implementations\ReceiptValidator.pas',
  UserRepositoryIntf in 'Repositories\Interfaces\UserRepositoryIntf.pas',
  UserRepository in 'Repositories\Implementations\UserRepository.pas',
  ProductRepositoryIntf in 'Repositories\Interfaces\ProductRepositoryIntf.pas',
  ProductRepository in 'Repositories\Implementations\ProductRepository.pas',
  CustomerRepositoryIntf in 'Repositories\Interfaces\CustomerRepositoryIntf.pas',
  CustomerRepository in 'Repositories\Implementations\CustomerRepository.pas',
  CashRegisterRepositoryIntf in 'Repositories\Interfaces\CashRegisterRepositoryIntf.pas',
  CashRegisterRepository in 'Repositories\Implementations\CashRegisterRepository.pas',
  CashMovementRepositoryIntf in 'Repositories\Interfaces\CashMovementRepositoryIntf.pas',
  CashMovementRepository in 'Repositories\Implementations\CashMovementRepository.pas',
  SaleRepositoryIntf in 'Repositories\Interfaces\SaleRepositoryIntf.pas',
  SaleRepository in 'Repositories\Implementations\SaleRepository.pas',
  SaleItemRepositoryIntf in 'Repositories\Interfaces\SaleItemRepositoryIntf.pas',
  SaleItemRepository in 'Repositories\Implementations\SaleItemRepository.pas',
  SalePaymentRepositoryIntf in 'Repositories\Interfaces\SalePaymentRepositoryIntf.pas',
  SalePaymentRepository in 'Repositories\Implementations\SalePaymentRepository.pas',
  AccountReceivableRepositoryIntf in 'Repositories\Interfaces\AccountReceivableRepositoryIntf.pas',
  AccountReceivableRepository in 'Repositories\Implementations\AccountReceivableRepository.pas',
  StockMovementRepositoryIntf in 'Repositories\Interfaces\StockMovementRepositoryIntf.pas',
  StockMovementRepository in 'Repositories\Implementations\StockMovementRepository.pas',
  ReceiptRepositoryIntf in 'Repositories\Interfaces\ReceiptRepositoryIntf.pas',
  ReceiptRepository in 'Repositories\Implementations\ReceiptRepository.pas',
  User in 'Domain\Entities\User.pas',
  Product in 'Domain\Entities\Product.pas',
  Customer in 'Domain\Entities\Customer.pas',
  CashRegister in 'Domain\Entities\CashRegister.pas',
  CashMovement in 'Domain\Entities\CashMovement.pas',
  Sale in 'Domain\Entities\Sale.pas',
  SaleItem in 'Domain\Entities\SaleItem.pas',
  SalePayment in 'Domain\Entities\SalePayment.pas',
  AccountReceivable in 'Domain\Entities\AccountReceivable.pas',
  AccountReceivablePayment in 'Domain\Entities\AccountReceivablePayment.pas',
  StockMovement in 'Domain\Entities\StockMovement.pas',
  Receipt in 'Domain\Entities\Receipt.pas',
  ReceiptItem in 'Domain\Entities\ReceiptItem.pas',
  CashRegisterDomainServiceIntf in 'Domain\Services\Interfaces\CashRegisterDomainServiceIntf.pas',
  CashRegisterDomainService in 'Domain\Services\Implementations\CashRegisterDomainService.pas',
  SaleDomainServiceIntf in 'Domain\Services\Interfaces\SaleDomainServiceIntf.pas',
  SaleDomainService in 'Domain\Services\Implementations\SaleDomainService.pas',
  AccountReceivableDomainServiceIntf in 'Domain\Services\Interfaces\AccountReceivableDomainServiceIntf.pas',
  AccountReceivableDomainService in 'Domain\Services\Implementations\AccountReceivableDomainService.pas',
  StockMovementDomainServiceIntf in 'Domain\Services\Interfaces\StockMovementDomainServiceIntf.pas',
  StockMovementDomainService in 'Domain\Services\Implementations\StockMovementDomainService.pas',
  ReceiptDomainServiceIntf in 'Domain\Services\Interfaces\ReceiptDomainServiceIntf.pas',
  ReceiptDomainService in 'Domain\Services\Implementations\ReceiptDomainService.pas',
  PasswordHasher in 'Utils\PasswordHasher.pas',
  AuthDtos in '..\HiDriver.Shared\DTOs\Auth\AuthDtos.pas',
  ProductDtos in '..\HiDriver.Shared\DTOs\Products\ProductDtos.pas',
  CustomerDtos in '..\HiDriver.Shared\DTOs\Customers\CustomerDtos.pas',
  CashRegisterDtos in '..\HiDriver.Shared\DTOs\CashRegister\CashRegisterDtos.pas',
  CashRegisterStatusEnum in '..\HiDriver.Shared\Enums\CashRegisterStatusEnum.pas',
  CashMovementTypeEnum in '..\HiDriver.Shared\Enums\CashMovementTypeEnum.pas',
  SaleDtos in '..\HiDriver.Shared\DTOs\Sales\SaleDtos.pas',
  SaleStatusEnum in '..\HiDriver.Shared\Enums\SaleStatusEnum.pas',
  PaymentMethodEnum in '..\HiDriver.Shared\Enums\PaymentMethodEnum.pas',
  AccountReceivableDto in '..\HiDriver.Shared\DTOs\AccountsReceivable\AccountReceivableDto.pas',
  AccountReceivableStatusEnum in '..\HiDriver.Shared\Enums\AccountReceivableStatusEnum.pas',
  StockMovementDto in '..\HiDriver.Shared\DTOs\StockMovements\StockMovementDto.pas',
  StockMovementTypeEnum in '..\HiDriver.Shared\Enums\StockMovementTypeEnum.pas',
  StockMovementSourceTypeEnum in '..\HiDriver.Shared\Enums\StockMovementSourceTypeEnum.pas',
  ReceiptDto in '..\HiDriver.Shared\DTOs\Receipts\ReceiptDto.pas',
  ReceiptSourceTypeEnum in '..\HiDriver.Shared\Enums\ReceiptSourceTypeEnum.pas',
  ReceiptStatusEnum in '..\HiDriver.Shared\Enums\ReceiptStatusEnum.pas',
  DatabaseConnectionIntf in 'Data\Connection\Interfaces\DatabaseConnectionIntf.pas',
  DatabaseConnection in 'Data\Connection\Implementations\DatabaseConnection.pas',
  TransactionManagerIntf in 'Data\Transactions\Interfaces\TransactionManagerIntf.pas',
  TransactionManager in 'Data\Transactions\Implementations\TransactionManager.pas',
  DatabaseInitializerIntf in 'Data\Scripts\Interfaces\DatabaseInitializerIntf.pas',
  DatabaseInitializer in 'Data\Scripts\Implementations\DatabaseInitializer.pas';

var
  Config: IApiConfig;
  Bootstrap: IAppBootstrap;

begin
  try
    Config := TApiConfig.Create;
    Bootstrap := TAppBootstrap.Create(Config);
    Bootstrap.Execute;
  except
    on E: Exception do
      Writeln(E.ClassName, ': ', E.Message);
  end;
end.
